site_name: smdrr's note
site_url: https://example.com/
repo_url: https://github.com/smdrr11037/my_site
nav:
  - Home: index.md
  - Ads: 
      - Part 1: ./ads/ads_part_1.md
      - Part 2: ./ads/ads_part_2.md 
      - Test Interface: ./ads/project2_test.md
  - CO:
      - Chapter 1、3: ./CO/CO.md
      - Chapter 2: CO/CO_2.md
  - oop:
      - Basis: ./oop/oop.md
      - Implementatin: ./oop/oop2.md
  - DataBase:
      - Introduction: ./DataBase/DataBase.md
      - Use sql: ./DataBase/DataBase2.md
  - 备忘: memoire.md

  - DailyLife: ./DailyLife/DailyLife.md
  
  - OC: OC/oc.md

theme:
  custom_dir: overrides
  logo: img/IMG_2839.PNG
  repo: img/IMG_2840.PNG
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  favicon: img/favicon.ico
  name: 'material'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
  palette:

    # Toggle light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode


extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
  - javascripts/custom.js

extra_css: [extra.css]

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra:
  img_path: /img
  js_path: /javascripts