site_name: smdrr's note
site_url: https://example.com/
repo_url: https://github.com/smdrr11037/my_site
nav:
  - Home: index.md
  - Ads: 
      - Part 1: ./ads/ads_part_1.md
  - 备忘: memoire.md
# theme:
#   name: material
#   palette:
#     primary: blue gray
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js