site_name: smdrr's note
site_url: https://example.com/
repo_url: https://github.com/smdrr11037/my_site
nav:
  - Home: index.md
  - Past:
    - Ads: 
        - Part 1: ./ads/ads_part_1.md
        - Part 2: ./ads/ads_part_2.md 
        - Part 3(开始算法分析): ./ads/ads_part_3.md
        - Part 4: ./ads/ads_part_4.md
        - Test Interface: ./ads/project2_test.md
    - CO:
        - Chapter 1、3: ./CO/CO.md
        - Chapter 2 (Instructions): CO/CO_2.md
        - Chapter 4 (Processor): CO/CO_3.md
        - Chapter 5 (Memory): CO/CO_4.md
        - Chapter 6 (I/O): CO/CO_5.md
        
    - oop:
        - Basis: ./oop/oop.md
        - Implementatin: ./oop/oop2.md
        - Inheritance: ./oop/oop3.md
        - Polymorphism: ./oop/oop4.md
        - Encapsulation: ./oop/oop5.md
    - DataBase:
        - Introduction: ./DataBase/DataBase.md
        - Use SQL: ./DataBase/DataBase2.md
        - Advanced SQL: ./DataBase/DataBase3.md
        - E-R Model: ./DataBase/DataBase4.md
        - Relational Database Design: ./DataBase/DataBase5.md
        - Storage and Indexing: ./DataBase/DataBase6.md
        - Query Processing: ./DataBase/DataBase7.md
        - Transaction Management: ./DataBase/DataBase8.md
    - Matlab: ./Matlab/Matlab.md
  - Reasearch:
      - 文献阅读: ./Research/read.md
  - 优化:
      - part1: ./Opt/Opt1.md
  - TOC:
      - part1: ./TOC/TOC1.md
  - OS:
      - part1: ./OS/OS1.md
  - CN:
      - part1: ./CN/CN1.md
      - 物理层: ./CN/CN2.md
  - CA:
      - part1: ./CA/CA1.md
  - asm:
      - part1: ./asm/asm1.md
  - 备忘: 
      - Home: memoire.md
      

  - DailyLife: ./DailyLife/DailyLife.md
  
  # - OC: OC/oc.md

theme:
  # custom_dir: overrides
  logo: img/IMG_2839.PNG
  repo: img/IMG_2840.PNG
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  favicon: img/favicon.ico
  name: 'material'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
  palette:

    # Toggle light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode


extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
  - javascripts/custom.js

extra_css: [extra.css]

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra:
  img_path: /img
  js_path: /javascripts